name: CI - Dev Branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Pull data from DVC
      run: |
        dvc pull
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
    - name: Post results with CML
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## 🧪 Pytest Results" > report.md
        pytest -v >> report.md
        cml comment create report.md
